language: java
sudo: true
dist: trusty
jdk: oraclejdk9
addons:
  apt:
    packages:
      - oracle-java9-installer
before_install:
  - chmod +x mvnw
after_success:
- mvn clean cobertura:cobertura coveralls:report
deploy:
  provider: openshift
  user: csankara@in.ibm.com
  password:
    secure:7t4Bxt0nYjOjLNIpp9boNst5evmHvOxpf-T5UXpRKGk
  app: angular11
  domain: csankara
  on:
    repo: Sankar-ibm/helloworld

